### PR TITLE
Added ability to directly export (and read) gzipped CIFF

### PR DESCRIPTION
**Pull request by lintool**
Also:
+ Added Apache License header
+ Ability to to specify CIFF description from command-line

### CODE REVIEW

**Comment by cmacdonald** [comment]
Why not just check the output filename and use gzip compression if it ends with .gz?

**Comment by lintool** [comment]
@cmacdonald good call, will implement.

**Comment by lintool** [comment]
@cmacdonald what you intended?

**Comment by cmacdonald** [comment]
lgtm

**Pull request merged**
